# Generated by Django 4.1.1 on 2022-12-19 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_producto')),
                ('cantidad', models.IntegerField()),
                ('lote', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
