# Generated by Django 4.1.1 on 2022-12-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_productos_id_alter_productos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.CharField(max_length=30),
        ),
    ]
