# Generated by Django 4.1.1 on 2022-12-24 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_producto'),
        ),
    ]
