# Generated by Django 4.1.1 on 2022-12-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('genero', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Otro')])),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('genero', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Otro')])),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('imdb', models.IntegerField()),
                ('actores', models.ManyToManyField(to='movie.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.paises'),
        ),
        migrations.AddField(
            model_name='actor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.paises'),
        ),
    ]
