# Generated by Django 4.1.1 on 2022-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(to='movie.genero'),
        ),
    ]
