# Generated by Django 4.1.1 on 2022-12-26 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_pelicula_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 20, 49, 31, 498101, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
